<a href="https://colab.research.google.com/github/pragneshrana/DeepLearning/blob/master/GettingStarted/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy
numerical library for python

In [2]:
import numpy as np
x = np.array([1,2,3])
print(x)
print(type(x))


[1 2 3]
<class 'numpy.ndarray'>


In [4]:
l = [4,5,6]
l = np.array((l))
print(l)
print(type(x))


[4 5 6]
<class 'numpy.ndarray'>


In [6]:
X = np.asarray(l,float)

In [7]:
print(X)
X.shape

[4. 5. 6.]


(3,)

In [8]:
np.array?

In [9]:
X = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [10]:
print(X)
X.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

# Accessing elements:

In [11]:
X[0,0] #specific element (row,col)

1

In [12]:
X[:,1] #2nd row

array([2, 5, 8])

In [14]:
X = np.zeros((4,5))
print(X)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
X = np.eye(4,5) #Identity matrix
print(X)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [19]:
X = np.random.random((4,5)) #random matrix
print(X)

[[0.54169486 0.95584796 0.64952127 0.78296823 0.02735652]
 [0.10952971 0.38030599 0.71066949 0.05705633 0.19453325]
 [0.05119338 0.07940097 0.55416276 0.9115779  0.44783495]
 [0.25697191 0.28854028 0.83472127 0.21302609 0.0753233 ]]


In [20]:
Z = X.T #transpose
print(Z)

[[0.54169486 0.10952971 0.05119338 0.25697191]
 [0.95584796 0.38030599 0.07940097 0.28854028]
 [0.64952127 0.71066949 0.55416276 0.83472127]
 [0.78296823 0.05705633 0.9115779  0.21302609]
 [0.02735652 0.19453325 0.44783495 0.0753233 ]]


In [22]:
Y = Z.reshape(X.shape[0]*X.shape[1],1)
print(Y)

[[0.54169486]
 [0.10952971]
 [0.05119338]
 [0.25697191]
 [0.95584796]
 [0.38030599]
 [0.07940097]
 [0.28854028]
 [0.64952127]
 [0.71066949]
 [0.55416276]
 [0.83472127]
 [0.78296823]
 [0.05705633]
 [0.9115779 ]
 [0.21302609]
 [0.02735652]
 [0.19453325]
 [0.44783495]
 [0.0753233 ]]


In [24]:
A = np.arange(5)
B = np.arange(5)

#element wise operation
C = A+B
D = A-B
E = A*B
print(C,D,E)

[0 2 4 6 8] [0 0 0 0 0] [ 0  1  4  9 16]


In [25]:
print(A,A+1)


[0 1 2 3 4] [1 2 3 4 5]


In [26]:
A = np.random.random((2,3))

In [27]:
print(A)

[[0.51058719 0.38974494 0.45874089]
 [0.23816745 0.1606144  0.40545754]]


In [29]:
print(A+1)

[[1.51058719 1.38974494 1.45874089]
 [1.23816745 1.1606144  1.40545754]]


In [30]:
A = np.floor(np.random.random((2,3))*10)
print(A)

[[9. 5. 4.]
 [7. 3. 1.]]


In [35]:
u = [1,2,3]
v = [-1,0,1]

p1= np.inner(u,v)
print(p1)

2


In [34]:
p2 = np.outer(u,v)
print(p2)

[[-1  0  1]
 [-2  0  2]
 [-3  0  3]]


In [36]:
A = np.ones((2,3))
B = np.ones((3,6))

np.dot(A,B)

array([[3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.]])

In [39]:
A.sum()

6.0

In [40]:
A.sum(axis = 0) #colm wise sum

array([2., 2., 2.])

In [41]:
A.sum(axis = 1) #row wise sum

array([3., 3.])