<a href="https://colab.research.google.com/github/pragneshrana/DeepLearning/blob/master/GettingStarted/Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Vectors

# What are vectors?  
Collection of cordinates of point in given space. \\ 
It has, \\
1. Magnitude $\rightarrow \sqrt{x_1^2 + x_2^2}$
2. Direction 

# Eucliden Space (Can Ignore)
In geomrtey, a two or three dimentional space in which the axioms and posulates of euclidean geometry apply is euclidean space. \\
A space in any finite number of dimensions, in which points are designated by coordinates and the distance between two points is given by a distance formula. $\sqrt{\sum_{i}^{N}x_i^2}$

# Dot Product 
u = $[u_1 \space u_2]$ \\
v = $[v_1 \space v_2]$ \\
$u \cdot v = u^Tv  = \sum_i u_i v_i$


# Unit Vector
Any vector with magnitude 1 is called unit vector \\
$||(2,1.5)|| = \sqrt{2^2+1.5^2} =\sqrt{6.25} = 2.5$ is not a unit vector. \\
but normalization of vector by its magnitude can give unit vector. \\
$(2/2.5,1.5/2.5)$ is unit vector.

# Projection of vector onto another vector
projectio of x on y $\rightarrow  proj_{x}y$ = $\bigg(\frac{x \cdot y}{||y||^2}\bigg)\cdot y$ = = $({x \cdot y})\cdot \frac{y}{||y||^2}$

# Angle between two vectors
$x\cdot y$ = $||x|| ||y|| \cos \theta$ \\
$\cos \theta = \frac{x \cdot y}{||x|| ||y||}$

# Orthogonal Vectors (Perpendicular to each other)
dot product of two vector is zero \\
$x\cdot y$ = $||x|| ||y|| \cos \theta = 0 \rightarrow \theta = 90$ \\


# Why do we care about vector?
ex: find out weather mobile phone is going to hit the market or not \\

[BatteryUse ScrrenSize FM-Yes FM-NO Price] = [151 6 1 0 15000] \\

Anything can be described in the form of vector using number. 


likewise you describe the employee, \\
[Salary MonthWorked Training Skill] \\

Anything can be described using vector.

#Matrices

$
\begin{bmatrix}
 2 & 3 & 4 \\
 4 & 5 & 6 \\
 7 & 8 & 9 \\
\end{bmatrix}$ is an $\mathcal{R}^{3X3}$  \\
where, ${R}^{mXn}$ denotes the Row Vector and Column Vector



In [ ]:
import numpy as np
A = np.random.random((3,3)) 
print(A)

[[0.18107564 0.81087955 0.09345283]
 [0.18668725 0.95675061 0.03676896]
 [0.07074953 0.59600726 0.90964753]]


In [ ]:
B = np.random.random((3,3)) 
print(B)

[[0.34114518 0.5984782  0.06892455]
 [0.19518858 0.19390501 0.43521715]
 [0.62515244 0.34660619 0.85281112]]


Matrix Addition:

In [ ]:
A+B

array([[0.52222082, 1.40935775, 0.16237738],
       [0.38187584, 1.15065562, 0.4719861 ],
       [0.69590198, 0.94261344, 1.76245864]])

Matrix Vector Multiplication:

When matrix hits the vector, vector gets transformed.

In [ ]:
x = np.random.random((3,1))
print('x :\n',x)

b  = np.dot(A,x)

x :
 [[0.94786932]
 [0.7480069 ]
 [0.22998954]]


Matrix Matrix Multiplication:

In [ ]:
C = np.matmul(A,B)
print(C)

[[0.27846978 0.29799476 0.44508685]
 [0.27342046 0.30999134 0.46061858]
 [0.70913805 0.47320031 1.04002648]]
